### PR TITLE
Small step map layout fixes

### PR DESCRIPTION
**Pull request by lidavidm**

### CODE REVIEW

**Comment by lidavidm** [comment]
[reduct.mp4.zip](https://github.com/ianarawjo/lcalcgame/files/1383722/reduct.mp4.zip)

**Comment by ianarawjo** [comment]
Wonderful!!! It is very nice.

**Comment by ianarawjo** [comment]
I think the only remaining issue is layout -- the preview array sometimes goes off-screen. What should we do about this? (it will come up in the last few map levels) I think the issue is with the auto-centering of the array expr after one reduction. This can put the result off the screen. Perhaps we can first check whether the expr fits on screen -- if it doesn't, don't re-center the array? (Or maybe the array is auto-centering because of anchor, so we'll have to change the anchor.)

After this is resolved I'll send the game out to Yishu. 

Today I am working on:
- fixing bugs in the Hour of Code progression
- re-creating the CF progression for our elementary school study
- continuing the game rewrite (shh)

**Comment by ianarawjo** [comment]
Oh a small issue to fix as well -- make sure to lock subexpressions for the exprs in the preview array... Booleans inside conditionals can be dragged out. :)

**Comment by lidavidm** [comment]
@ianarawjo The auto-centering is intended to make sure that at least one reducible expression is always visible, so even though it goes off screen, they should still be able to interact with it. We could try and lay out expressions vertically, though this isn't so convenient right now. I'll fix the small issue - is there anything else to look at?

**Comment by ianarawjo** [comment]
Yes but the auto-centering actually makes the leftmost expression go off screen (the result of the reduction). A better check would be checking if the array goes off-screen after reduction. I haven't seen a case that you mention, where the right expressions are actually offscreen *after* the reduction.

**Comment by lidavidm** [comment]
Ah okay, I'll make sure it works in all cases then.

**Pull request merged**
