### PR TITLE
Fix typing, improve performance

### PR DESCRIPTION
**Pull request by lidavidm**
@ianarawjo This fixes the typing issue and improves performance while typing. FWIW, logging calls seem to slow down typing drastically; here's a screenshot of a profile showing that the logging calls inflate frame time to 60ms(!).

image

### CODE REVIEW

**Comment by ianarawjo** [comment]
Typing is still broken and the game actually seems slower -- maybe the changes didn't merge properly?

**Comment by ianarawjo** [comment]
Ah -- so typing is broken, that's true, but the slowness seems to stem from the static logging (+cache), not anything in a recent commit. I'll disable the local cache'ing for now.

**Comment by lidavidm** [comment]
Ah, didn't notice `ContextualTypeInTextExpr` also has side effects on `canReduce`, let me take a look

**Comment by ianarawjo** [comment]
I fixed it.

**Comment by lidavidm** [comment]
Oh ok. Is there anything else that needs changing before this afternoon?

**Comment by ianarawjo** [comment]
The progression needs some tweaking -- are you around Gates? Could you meet shortly? We could make these changes together.

**Comment by lidavidm** [comment]
I'm not there currently I could be there around 1:15 or so

**Comment by ianarawjo** [comment]
That would be great.

**Pull request merged**
