### PR TITLE
Update later chapters with new fading system

### PR DESCRIPTION
**Pull request by lidavidm**

### CODE REVIEW

**Comment by lidavidm** [comment]
@ianarawjo I touched up the last chapter. We do need one more fix though - right now, variables in JavaScript are hard-coded to be LambdaVarExpr, but at some point it needs to switch over to VarExpr.

**Comment by ianarawjo** [comment]
@lidavidm Do you mean variables don't go through the ExprManager?

**Comment by lidavidm** [comment]
`parseES6` creates a `LambdaVarExpr` (`return new (ExprManager.getClass('var'))(node.name);`) for any `Identifier` node. So either at some point, it should switch over to creating `VarExpr` (`ExprManager.getClass('reference')`) or we need some other way to create mutable-variables.

**Comment by ianarawjo** [comment]
@lidavidm Is VarExpr just a more faded version of LambdaVarExpr?
Also, the current merge was broken: I got the error "NotchSnappable is not defined." I've recommit with the offending line commented out.

**Comment by lidavidm** [comment]
Ah, whoops, sorry about that - that was WIP.

We could use VarExpr as a more faded version of LambdaVarExpr. Right now they're in separate categories in `ExprManager` but maybe it makes sense to just merge them.

**Pull request merged**
